### ISSUE TITLE
Valuesets names are not unique

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#16]

**Comment by Wauplin** [comment]
I have been able to reproduce this issue. 
`Quantity` is not the only class that is generated twice. I used pylint to track them.

```
pylint --disable=all --enable=E0102 pydantic_fhir/r4.py
************* Module pydantic_fhir.r4
pydantic_fhir/r4.py:533:0: E0102: class already defined line 520 (function-redefined)
pydantic_fhir/r4.py:1701:0: E0102: class already defined line 1696 (function-redefined)
pydantic_fhir/r4.py:1706:0: E0102: class already defined line 1696 (function-redefined)
pydantic_fhir/r4.py:3045:0: E0102: class already defined line 3034 (function-redefined)
pydantic_fhir/r4.py:4480:0: E0102: class already defined line 4461 (function-redefined)
pydantic_fhir/r4.py:4725:0: E0102: class already defined line 4704 (function-redefined)
pydantic_fhir/r4.py:20731:0: E0102: class already defined line 5069 (function-redefined)
pydantic_fhir/r4.py:27898:0: E0102: class already defined line 27328 (function-redefined)
pydantic_fhir/r4.py:28009:0: E0102: class already defined line 27953 (function-redefined)
pydantic_fhir/r4.py:28022:0: E0102: class already defined line 27966 (function-redefined)
pydantic_fhir/r4.py:28039:0: E0102: class already defined line 27983 (function-redefined)
pydantic_fhir/r4.py:28052:0: E0102: class already defined line 27996 (function-redefined)

------------------------------------------------------------------
Your code has been rated at 9.97/10 (previous run: 9.97/10, +0.00)
```

More worrying, I found a class that is define twice but with a different definition : 
```
# this inherits from string as well so we can serialzie it correctly with pydantic
class MedicationStatusCodes(str, DocEnum):
    active = "active", """The medication is still being taken. """
    completed = "completed", """The medication is no longer being taken. """
    enteredInError = "entered-in-error", """Some of the actions that are implied by the medication statement may have occurred.  For example, the patient may have taken some of the medication.  Clinical decision support systems should take this status into account. """
    intended = "intended", """The medication may be taken at some time in the future. """
    stopped = "stopped", """Actions implied by the statement have been permanently halted, before all of them occurred. This should not be used if the statement was entered in error. """
    onHold = "on-hold", """Actions implied by the statement have been temporarily halted, but are expected to continue later. May also be called 'suspended'. """
    unknown = "unknown", """The state of the medication use is not currently known. """
    notTaken = "not-taken", """The medication was not consumed by the patient """
    
# this inherits from string as well so we can serialzie it correctly with pydantic
class MedicationStatusCodes(str, DocEnum):
    active = "active", """The medication is available for use. """
    inactive = "inactive", """The medication is not available for use. """
    enteredInError = "entered-in-error", """The medication was entered in error. """
```

Based on these findings, I propose to :
- understand why this is happening and try to find a solution
- write a test that checks for duplicate classes based on pylint and add it to the github checks

**Comment by Wauplin** [comment]
Duplicated classes seem to come from duplicated definitions in the FHIR documentation. This is sad since we do not control that part.

Those two valuesets are not consistent but shares the same `name`/`title`/`definition`. Only difference is the `OID` and `Expansion` (the values). They have been published the same day so it's not that one is deprecated and not the other.
http://hl7.org/fhir/valueset-medication-status.html
http://hl7.org/fhir/valueset-medication-statement-status.html

**Other examples (not exhaustive) :**

- Duplicated ValueSet class : `AlternativeCodeKind`
    - http://terminology.hl7.org/CodeSystem/composition-altcode-kind
    - http://terminology.hl7.org/CodeSystem/codesystem-altcode-kind

- Duplicated ValueSet class : `ContractResourceScopeCodes`
    - http://hl7.org/fhir/contract-security-category
    - http://hl7.org/fhir/contract-security-classification
    - http://hl7.org/fhir/contract-scope

- Duplicated ValueSet class : `FHIRDeviceStatus`
    - http://hl7.org/fhir/device-definition-status
    - http://hl7.org/fhir/device-status

- Duplicated ValueSet class : `MedicationStatusCodes`
    - http://hl7.org/fhir/CodeSystem/medication-statement-status
    - http://hl7.org/fhir/CodeSystem/medication-status

- Duplicated ValueSet class : `ObservationCategoryCodes`
    - http://terminology.hl7.org/CodeSystem/observation-category
    - http://hl7.org/fhir/secondary-finding

**EDIT :**
According to the documentation, we must not consider the names as unique : `Comments : The name is not expected to be globally unique. The name should be a simple alphanumeric type name to ensure that it is machine-processing friendly.A name should be provided unless the value set is a contained resource (e.g. an anonymous value set in a profile). Most registries will require a name.` ( https://www.hl7.org/fhir/valueset-definitions.html )

**Comment by julian-r** [comment]
Lets generate the names then from the URL.
 - We make a configurable prefix mapping in `generator.yaml`
 - We composit the name from the url prefix and the suffix:
 E.g.

`http://hl7.org/fhir/secondary-finding`

`http://hl7.org/fhir/` -> `FHIR`

`secondary-finding` -> `SecondaryFinding`

So the total composited name would be:
`FHIRSecondaryFinding`

**Comment by Wauplin** [comment]
Following @trojanowski advice, I looked into the JSON schema description to see how valuesets are refered to when describing the resources. It seems that it always refers to the URI/URL. 

**Examples :**

- `medication.profile.json`
```json
{
  "resourceType": "StructureDefinition",
  "id": "Medication",
   (...)
  "snapshot": {
    "element": [
        (...)
          {
            "id": "Medication.status",
            "path": "Medication.status",
            "short": "active | inactive | entered-in-error",
            (...)
            "binding": {
                "extension": [(...)],
                 "strength": "required",
                 "description": "A coded concept defining if the medication is in active use.",
                 "valueSet": "http://hl7.org/fhir/ValueSet/medication-status|4.0.1"
            }
(...)
```

- `medicationstatement.profile.json`
```json
{
  "resourceType": "StructureDefinition",
  "id": "MedicationStatement",
   (...)
  "snapshot": {
    "element": [
       (...)
       {
          "id": "MedicationStatement.status",
          "path": "MedicationStatement.status",
          "short": "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken",
          (...)
          "binding": {
              "extension": [(...)],
              "strength": "required",
              "description": "A coded concept indicating the current status of a MedicationStatement.",
              "valueSet": "http://hl7.org/fhir/ValueSet/medication-statement-status|4.0.1"
        },
(...)
```

**In the code :**
The binding is then used in the code to bind a resource or element to the corresponding ValueSet.

See https://github.com/skalarsystems/fhirzeug/blob/master/fhirzeug/fhirspec.py#L1026
```py
        # resolve bindings
        if (
            self.binding is not None
            and self.binding.is_required
            and self.binding.has_valueset
        ):
            uri = self.binding.valueset_uri
           (...)

           if "http://hl7.org/fhir" != uri[:19]: # --> We consider all that all valuesets come from official FHIR
                logger.debug('Ignoring foreign ValueSet "{}"'.format(uri))
                return
           (...)

            valueset = self.element.profile.spec.valueset_with_uri(uri)
            # --> This returns a FHIRValueSet object given an URI.
```
This means that the code is already using the URI to make the link between a `FHIRStructureDefinitionElementDefinition` object and a `FHIRValueSet` object. With a bit of chance, the "only" thing that need to be changed is how the element name is rendered in jinja.
At the moment, several parts of the code are refering to the `enum_namemap` dictionnary from the setting and to the `safe_enum_name` method from `FHIRSpec` : 
```py
self.url = resource.get("url")
if self.url in self.spec.settings.enum_namemap:
    self.name = self.spec.settings.enum_namemap[self.url]
else:
    self.name = self.spec.safe_enum_name(resource.get("name"), ucfirst=True)
if len(self.name) < 1:
    raise Exception(
        f"Unable to create a name for enum of system {self.url}. You may need to specify a name explicitly in mappings.enum_namemap. Code system content: {resource}"
    )
```

**Suggestion**
So what I suggest is to try to add the exceptions in the `enum_namemap` dictionary that is already suppose to work. I'll give it a try and let you know. If we go for this solution, we will need an automatic test to check that no classes are duplicated but that shouldn't be a problem.

If it doesn't work or if the `enum_namemap` increases to much, we could try to change the way we compute the `safe_enum_name` method using behavior proposed by @julian-r just above (on URLs, not names).

**NB :**
- I might be confusing `ValueSet` and `CodeSystem` concepts. I don't really get the difference between those two yet.
- `Quantity` is a `BackboneElement`, not a `ValueSet`. Hopefully, a similar fix would be possible for it.

**Comment by Wauplin** [comment]
It has been decided to go for the `enum_namemap` workaround that is already implemented.
I'm starting to work on it + implement the associated test.
