### ISSUE TITLE
date validation does not work

### ISSUE THREAD

**Issue by julian-r** [skalarsystems/fhirzeug#22]
Validation of date time seems to be not working correctly, any number will validate. But not letters.
We need to check why the [proposed regex](https://www.hl7.org/fhir/datatypes.html#date) does not work correctly here.

**Comment by auerj** [comment]
@Wauplin it seems that the regex is kind of working but not validating if the resulting values are correct. for example the 33rd of march would pass the regex validation.

**Comment by Wauplin** [comment]
@auerj thanks, I was just about to comment this issue.

I found out two things :
- First, FHIR gives examples of valid matches. Especially, `2015-02-07T13:28:17-05:00` is valid but not `2015-02-07T13:28:17` . I will add the FHIR examples to our tests.
- Second, pydantic validation on regex just need a match to be valid, not an exact pattern ( see : https://github.com/samuelcolvin/pydantic/blob/0cee311be59ca09cd29a66c344cd06fb304e9ddd/pydantic/types.py#L183 ). This is why `2019-06-33` pass the test even if it doesn't make sense. What I suggest is to add a `\A` and a `\Z` at beginning and end of every regex that pydantic validates. I succesfully tested it locally.
