### ISSUE TITLE
Use stringcase package everywhere it's needed

### ISSUE THREAD

**Issue by Wauplin** [skalarsystems/fhirzeug#24]
Stringcase allows string formatting between lowercase, uppercase, camelcase, snakecase,...
At the moment, some formatting are done manually and might introduce error.

For instance, I spotted this code in `fhirspec.py` :
```
 # CamelCase or just plain
if self.settings.camelcase_classes:
     return classname[:1].upper() + classname[1:]
return classname
```

Maybe we could generalize the use of stringcase package to avoid any issue.

**Comment by julian-r** [comment]
Totally agree on this.
