### ISSUE TITLE
Wrong behavior in `from_dict` when List is passed instead of Dict

### ISSUE THREAD

**Issue by Wauplin** [skalarsystems/fhirzeug#59]
In `Observation` resource, attribute `Subject` must receive 0..1 element of type `Reference`. When using the `from_dict` function, it must then be a dictionary and not a list. However if a list is passed, no error is raised and weird behavior happens. See example below :

Good example :
```py
resource = r4.from_dict(
    {
        "resourceType": "Observation",
        "status": "final",
        "code": {"coding": [{"system": "test", "code": "test"}]},
        "subject": {"reference": "a reference", "display": "REF"}, # Dictionary -> OK
    }
)
resource.subject
> Reference(id=None, extension=None, reference='a reference', type=None, identifier=None, display='REF')
```

Wrong type : 
```py
r4.from_dict(
    {
        "resourceType": "Observation",
        "status": "final",
        "code": {"coding": [{"system": "test", "code": "test"}]},
        "subject": [{"reference": "a reference", "display": "REF"}], # As a list -> not expected
    }
)
resource.subject
> Reference(id=None, extension=None, reference='display', type=None, identifier=None, display=None)
```

**Expected :** a `ValidationError` must be raised.

**Comment by Wauplin** [comment]
I isolated a very simple example : 

```py
import pydantic
import typing


class Foo(pydantic.BaseModel):
    field_a: typing.Optional[str]
    field_b: typing.Optional[str]


class Model(pydantic.BaseModel):
    field_c: Foo


Model(field_c={"field_a": "123", "field_b": "456"})
# Model(field_c=Foo(field_a='123', field_b='456'))

Model(field_c=[{"field_a": "123", "field_b": "456"}])
# Model(field_c=Foo(field_a='field_b', field_b=None))
```

I didn't get the time yet to investigate more what happens internally in pydantic.

**Comment by Wauplin** [comment]
I took some time today to investigate more this issue. 

From what I understand, here is what happens when running `Model(field_c=[{"field_a": "123", "field_b": "456"}])` (with list) :
- `Model` validation :
  - field_c is validated with value `[{"field_a": "123", "field_b": "456"}]`
  - field_c shape is a SINGLETON so `self._validate_singleton` is called
  - Value is validated with all validators for field_c (in practice only `Foo.validate` validator)
    - `Foo.validate` is called with value `[{"field_a": "123", "field_b": "456"}]` :
       - Validator is expecting a dictionary or an object as value but receives a list
       - List is converted to dict using `value_as_dict = dict(value)`
           - In practice : `[{"field_a": "123", "field_b": "456"}]  -> {'field_a': 'field_b'}`
       - Foo validator validate `{'field_a': 'field_b'}` which doesn't raise any error since `field_a` is a string and `field_b` is Optional

=> we end up with `Model(field_c=Foo(field_a='field_b', field_b=None))`

Here is the code of `Foo.validate` that does the conversion :
https://github.com/samuelcolvin/pydantic/blob/bf9cc4a5e7903ada2e819a63fe2da011f292a143/pydantic/main.py#L589

**Comment by Wauplin** [comment]
I think a reasonable quick fix can be to add a pre root validator to our pydantic models that checks a list is never provided for a Singleton field.

Another option is to post an issue on pydantic repo for that problem. But I'm not 100% sure it will be considered as an issue since pydantic always try to format to the desired type before raising a ValidationError (example: strings are automatically converted to float if a float field).

@julian-r @trojanowski An opinion on this subject ?

**Comment by trojanowski** [comment]
@Wauplin it seems it should be solved in Pydantic V2: <https://github.com/samuelcolvin/pydantic/issues/1268>. But the solution suggested in the PR is IMO OK before it's resolved on the Pydatic side.
